---
title: "Conformalized Forecasting using Machine Leaning models -- with stacked generalization"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Conformalized Forecasting using Machine Leaning models -- with stacked generalization}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# With Lasso and Ridge

```{r}
fit_func_ridge <- function(x, y)
{
 glmnet::cv.glmnet(x, y, alpha=0) # ridge
}

fit_func_lasso <- function(x, y)
{
 glmnet::cv.glmnet(x, y, alpha=1) # lasso 
}

stacking_models = list()
stacking_models[[1]] <- list(fit_func=fit_func_ridge, predict_func=predict)
stacking_models[[2]] <- list(fit_func=fit_func_lasso, predict_func=predict)
names(stacking_models) <- c("ridge", "lasso")
```

```{r fig.width=7.5}
(res1 <- ahead::mlf(AirPassengers, h=25L, lags=20L, stack=FALSE, stacking_models=stacking_models))
(res2 <- ahead::mlf(AirPassengers, h=25L, lags=20L, stack=TRUE, stacking_models=stacking_models))
(res3 <- ahead::mlf(USAccDeaths, h=25L, lags=20L, stack=FALSE, stacking_models=stacking_models))
(res4 <- ahead::mlf(USAccDeaths, h=25L, lags=20L, stack=TRUE, stacking_models=stacking_models))
(res5 <- ahead::mlf(fdeaths, h=25L, lags=20L, stack=FALSE, stacking_models=stacking_models))
(res6 <- ahead::mlf(fdeaths, h=25L, lags=20L, stack=TRUE, stacking_models=stacking_models))
(res7 <- ahead::mlf(WWWusage, h=25L, lags=20L, stack=FALSE, stacking_models=stacking_models))
(res8 <- ahead::mlf(WWWusage, h=25L, lags=20L, stack=TRUE, stacking_models=stacking_models))
```

```{r fig.width=7.5}
par(mfrow=c(1, 2))
plot(res1, main="Conformal ML with stacking \n with AirPassengers")
plot(res3, main="Conformal ML without stacking \n with USAccDeaths")
```
```{r fig.width=7.5}
par(mfrow=c(1, 2))
plot(res2, main="Conformal ML with stacking \n with AirPassengers")
plot(res4, main="Conformal ML without stacking \n with USAccDeaths")
```

```{r fig.width=7.5}
par(mfrow=c(1, 2))
plot(res5, main="Conformal ML with stacking \n with fdeaths")
plot(res7, main="Conformal ML without stacking \n with WWWusage")
```
```{r fig.width=7.5}
par(mfrow=c(1, 2))
plot(res6, main="Conformal ML with stacking \n with fdeaths")
plot(res8, main="Conformal ML without stacking \n with WWWusage")
```

