---
title: "Conformalized Forecasting using Machine Leaning models -- with stacked generalization"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Conformalized Forecasting using Machine Leaning models -- with stacked generalization}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# With GLMNET

```{r fig.width=7.5}
(res1 <- ahead::mlf(AirPassengers, h=25L, lags=20L, fit_func=glmnet::cv.glmnet, stack=FALSE))
(res2 <- ahead::mlf(AirPassengers, h=25L, lags=20L, fit_func=glmnet::cv.glmnet, stack=TRUE))
(res3 <- ahead::mlf(USAccDeaths, h=25L, lags=20L, fit_func=glmnet::cv.glmnet, stack=TRUE))
(res4 <- ahead::mlf(USAccDeaths, h=25L, lags=20L, fit_func=glmnet::cv.glmnet, stack=FALSE))
```

## `AirPassengers` forecasting plot

```{r fig.width=7.5}
par(mfrow=c(1, 2))
plot(res1, main="Conformal ML without stacking")
plot(res2, main="Conformal ML with stacking")
```

## `USAccDeaths` forecasting plot

```{r fig.width=7.5}
par(mfrow=c(1, 2))
plot(res3, main="Conformal ML with stacking")
plot(res4, main="Conformal ML without stacking")
```

