// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cosine_attention_cpp
NumericMatrix cosine_attention_cpp(NumericVector series, int window_size);
RcppExport SEXP _ahead_cosine_attention_cpp(SEXP seriesSEXP, SEXP window_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type series(seriesSEXP);
    Rcpp::traits::input_parameter< int >::type window_size(window_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(cosine_attention_cpp(series, window_size));
    return rcpp_result_gen;
END_RCPP
}
// exponential_attention_cpp
NumericMatrix exponential_attention_cpp(NumericVector series, double decay_factor);
RcppExport SEXP _ahead_exponential_attention_cpp(SEXP seriesSEXP, SEXP decay_factorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type series(seriesSEXP);
    Rcpp::traits::input_parameter< double >::type decay_factor(decay_factorSEXP);
    rcpp_result_gen = Rcpp::wrap(exponential_attention_cpp(series, decay_factor));
    return rcpp_result_gen;
END_RCPP
}
// dot_product_attention_cpp
NumericMatrix dot_product_attention_cpp(NumericVector series);
RcppExport SEXP _ahead_dot_product_attention_cpp(SEXP seriesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type series(seriesSEXP);
    rcpp_result_gen = Rcpp::wrap(dot_product_attention_cpp(series));
    return rcpp_result_gen;
END_RCPP
}
// scaled_dot_product_attention_cpp
NumericMatrix scaled_dot_product_attention_cpp(NumericVector series, double temperature);
RcppExport SEXP _ahead_scaled_dot_product_attention_cpp(SEXP seriesSEXP, SEXP temperatureSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type series(seriesSEXP);
    Rcpp::traits::input_parameter< double >::type temperature(temperatureSEXP);
    rcpp_result_gen = Rcpp::wrap(scaled_dot_product_attention_cpp(series, temperature));
    return rcpp_result_gen;
END_RCPP
}
// gaussian_attention_cpp
NumericMatrix gaussian_attention_cpp(NumericVector series, double sigma);
RcppExport SEXP _ahead_gaussian_attention_cpp(SEXP seriesSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type series(seriesSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(gaussian_attention_cpp(series, sigma));
    return rcpp_result_gen;
END_RCPP
}
// linear_attention_cpp
NumericMatrix linear_attention_cpp(NumericVector series);
RcppExport SEXP _ahead_linear_attention_cpp(SEXP seriesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type series(seriesSEXP);
    rcpp_result_gen = Rcpp::wrap(linear_attention_cpp(series));
    return rcpp_result_gen;
END_RCPP
}
// value_based_attention_cpp
NumericMatrix value_based_attention_cpp(NumericVector series, double sensitivity);
RcppExport SEXP _ahead_value_based_attention_cpp(SEXP seriesSEXP, SEXP sensitivitySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type series(seriesSEXP);
    Rcpp::traits::input_parameter< double >::type sensitivity(sensitivitySEXP);
    rcpp_result_gen = Rcpp::wrap(value_based_attention_cpp(series, sensitivity));
    return rcpp_result_gen;
END_RCPP
}
// hybrid_attention_cpp
NumericMatrix hybrid_attention_cpp(NumericVector series, double time_decay, double value_sensitivity);
RcppExport SEXP _ahead_hybrid_attention_cpp(SEXP seriesSEXP, SEXP time_decaySEXP, SEXP value_sensitivitySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type series(seriesSEXP);
    Rcpp::traits::input_parameter< double >::type time_decay(time_decaySEXP);
    Rcpp::traits::input_parameter< double >::type value_sensitivity(value_sensitivitySEXP);
    rcpp_result_gen = Rcpp::wrap(hybrid_attention_cpp(series, time_decay, value_sensitivity));
    return rcpp_result_gen;
END_RCPP
}
// parametric_attention_cpp
NumericMatrix parametric_attention_cpp(NumericVector series, double alpha, double beta);
RcppExport SEXP _ahead_parametric_attention_cpp(SEXP seriesSEXP, SEXP alphaSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type series(seriesSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(parametric_attention_cpp(series, alpha, beta));
    return rcpp_result_gen;
END_RCPP
}
// compute_context_vectors_cpp
NumericVector compute_context_vectors_cpp(NumericVector series, NumericMatrix attention_weights);
RcppExport SEXP _ahead_compute_context_vectors_cpp(SEXP seriesSEXP, SEXP attention_weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type series(seriesSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type attention_weights(attention_weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_context_vectors_cpp(series, attention_weights));
    return rcpp_result_gen;
END_RCPP
}
// compare_attention_mechanisms
List compare_attention_mechanisms(NumericVector series, int window_size, double decay_factor, double temperature, double sigma, double sensitivity);
RcppExport SEXP _ahead_compare_attention_mechanisms(SEXP seriesSEXP, SEXP window_sizeSEXP, SEXP decay_factorSEXP, SEXP temperatureSEXP, SEXP sigmaSEXP, SEXP sensitivitySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type series(seriesSEXP);
    Rcpp::traits::input_parameter< int >::type window_size(window_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type decay_factor(decay_factorSEXP);
    Rcpp::traits::input_parameter< double >::type temperature(temperatureSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type sensitivity(sensitivitySEXP);
    rcpp_result_gen = Rcpp::wrap(compare_attention_mechanisms(series, window_size, decay_factor, temperature, sigma, sensitivity));
    return rcpp_result_gen;
END_RCPP
}
// meboot_approx
NumericVector meboot_approx(NumericVector p, int n, NumericVector z, NumericVector desintxb);
RcppExport SEXP _ahead_meboot_approx(SEXP pSEXP, SEXP nSEXP, SEXP zSEXP, SEXP desintxbSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type desintxb(desintxbSEXP);
    rcpp_result_gen = Rcpp::wrap(meboot_approx(p, n, z, desintxb));
    return rcpp_result_gen;
END_RCPP
}
// meboot_part_rcpp
NumericMatrix meboot_part_rcpp(NumericVector x, int reps, NumericVector z, double xmin, double xmax, NumericVector desintxb, bool reachbnd);
RcppExport SEXP _ahead_meboot_part_rcpp(SEXP xSEXP, SEXP repsSEXP, SEXP zSEXP, SEXP xminSEXP, SEXP xmaxSEXP, SEXP desintxbSEXP, SEXP reachbndSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type reps(repsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< double >::type xmin(xminSEXP);
    Rcpp::traits::input_parameter< double >::type xmax(xmaxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type desintxb(desintxbSEXP);
    Rcpp::traits::input_parameter< bool >::type reachbnd(reachbndSEXP);
    rcpp_result_gen = Rcpp::wrap(meboot_part_rcpp(x, reps, z, xmin, xmax, desintxb, reachbnd));
    return rcpp_result_gen;
END_RCPP
}
// expand_sd_rcpp
NumericMatrix expand_sd_rcpp(NumericVector x, NumericMatrix ensemble, double fiv, double elbow, bool force_clt);
RcppExport SEXP _ahead_expand_sd_rcpp(SEXP xSEXP, SEXP ensembleSEXP, SEXP fivSEXP, SEXP elbowSEXP, SEXP force_cltSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type ensemble(ensembleSEXP);
    Rcpp::traits::input_parameter< double >::type fiv(fivSEXP);
    Rcpp::traits::input_parameter< double >::type elbow(elbowSEXP);
    Rcpp::traits::input_parameter< bool >::type force_clt(force_cltSEXP);
    rcpp_result_gen = Rcpp::wrap(expand_sd_rcpp(x, ensemble, fiv, elbow, force_clt));
    return rcpp_result_gen;
END_RCPP
}
// expand_sd_rcpp_fast
NumericMatrix expand_sd_rcpp_fast(NumericVector x, NumericMatrix ensemble, double fiv, double elbow);
RcppExport SEXP _ahead_expand_sd_rcpp_fast(SEXP xSEXP, SEXP ensembleSEXP, SEXP fivSEXP, SEXP elbowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type ensemble(ensembleSEXP);
    Rcpp::traits::input_parameter< double >::type fiv(fivSEXP);
    Rcpp::traits::input_parameter< double >::type elbow(elbowSEXP);
    rcpp_result_gen = Rcpp::wrap(expand_sd_rcpp_fast(x, ensemble, fiv, elbow));
    return rcpp_result_gen;
END_RCPP
}
// exact_rf_forecast
NumericVector exact_rf_forecast(NumericMatrix embed_mat, int h, int lags, Function predict_func, List model);
RcppExport SEXP _ahead_exact_rf_forecast(SEXP embed_matSEXP, SEXP hSEXP, SEXP lagsSEXP, SEXP predict_funcSEXP, SEXP modelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type embed_mat(embed_matSEXP);
    Rcpp::traits::input_parameter< int >::type h(hSEXP);
    Rcpp::traits::input_parameter< int >::type lags(lagsSEXP);
    Rcpp::traits::input_parameter< Function >::type predict_func(predict_funcSEXP);
    Rcpp::traits::input_parameter< List >::type model(modelSEXP);
    rcpp_result_gen = Rcpp::wrap(exact_rf_forecast(embed_mat, h, lags, predict_func, model));
    return rcpp_result_gen;
END_RCPP
}
// forecast_innovs_loop_cpp
NumericVector forecast_innovs_loop_cpp(NumericVector eps, NumericVector rts, double eps_prev, double omega, double alpha, double beta, unsigned int df, unsigned int h);
RcppExport SEXP _ahead_forecast_innovs_loop_cpp(SEXP epsSEXP, SEXP rtsSEXP, SEXP eps_prevSEXP, SEXP omegaSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP dfSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rts(rtsSEXP);
    Rcpp::traits::input_parameter< double >::type eps_prev(eps_prevSEXP);
    Rcpp::traits::input_parameter< double >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type df(dfSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(forecast_innovs_loop_cpp(eps, rts, eps_prev, omega, alpha, beta, df, h));
    return rcpp_result_gen;
END_RCPP
}
// forecast_innovs_loop_cpp2
NumericVector forecast_innovs_loop_cpp2(NumericVector eps, NumericVector rn, double eps_prev, double omega, double alpha, double beta, unsigned int df, unsigned int h);
RcppExport SEXP _ahead_forecast_innovs_loop_cpp2(SEXP epsSEXP, SEXP rnSEXP, SEXP eps_prevSEXP, SEXP omegaSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP dfSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rn(rnSEXP);
    Rcpp::traits::input_parameter< double >::type eps_prev(eps_prevSEXP);
    Rcpp::traits::input_parameter< double >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type df(dfSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(forecast_innovs_loop_cpp2(eps, rn, eps_prev, omega, alpha, beta, df, h));
    return rcpp_result_gen;
END_RCPP
}
// create_lags_cpp
NumericMatrix create_lags_cpp(NumericVector x, int k);
RcppExport SEXP _ahead_create_lags_cpp(SEXP xSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(create_lags_cpp(x, k));
    return rcpp_result_gen;
END_RCPP
}
// create_train_inputs_cpp
List create_train_inputs_cpp(NumericMatrix x, int k);
RcppExport SEXP _ahead_create_train_inputs_cpp(SEXP xSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(create_train_inputs_cpp(x, k));
    return rcpp_result_gen;
END_RCPP
}
// reformat_cpp
NumericMatrix reformat_cpp(NumericMatrix x, unsigned long int n_k);
RcppExport SEXP _ahead_reformat_cpp(SEXP xSEXP, SEXP n_kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< unsigned long int >::type n_k(n_kSEXP);
    rcpp_result_gen = Rcpp::wrap(reformat_cpp(x, n_k));
    return rcpp_result_gen;
END_RCPP
}
// rev_matrix_cpp
NumericMatrix rev_matrix_cpp(NumericMatrix x);
RcppExport SEXP _ahead_rev_matrix_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rev_matrix_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// rbind_vecmat_cpp
NumericMatrix rbind_vecmat_cpp(NumericVector y, NumericMatrix x);
RcppExport SEXP _ahead_rbind_vecmat_cpp(SEXP ySEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rbind_vecmat_cpp(y, x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ahead_cosine_attention_cpp", (DL_FUNC) &_ahead_cosine_attention_cpp, 2},
    {"_ahead_exponential_attention_cpp", (DL_FUNC) &_ahead_exponential_attention_cpp, 2},
    {"_ahead_dot_product_attention_cpp", (DL_FUNC) &_ahead_dot_product_attention_cpp, 1},
    {"_ahead_scaled_dot_product_attention_cpp", (DL_FUNC) &_ahead_scaled_dot_product_attention_cpp, 2},
    {"_ahead_gaussian_attention_cpp", (DL_FUNC) &_ahead_gaussian_attention_cpp, 2},
    {"_ahead_linear_attention_cpp", (DL_FUNC) &_ahead_linear_attention_cpp, 1},
    {"_ahead_value_based_attention_cpp", (DL_FUNC) &_ahead_value_based_attention_cpp, 2},
    {"_ahead_hybrid_attention_cpp", (DL_FUNC) &_ahead_hybrid_attention_cpp, 3},
    {"_ahead_parametric_attention_cpp", (DL_FUNC) &_ahead_parametric_attention_cpp, 3},
    {"_ahead_compute_context_vectors_cpp", (DL_FUNC) &_ahead_compute_context_vectors_cpp, 2},
    {"_ahead_compare_attention_mechanisms", (DL_FUNC) &_ahead_compare_attention_mechanisms, 6},
    {"_ahead_meboot_approx", (DL_FUNC) &_ahead_meboot_approx, 4},
    {"_ahead_meboot_part_rcpp", (DL_FUNC) &_ahead_meboot_part_rcpp, 7},
    {"_ahead_expand_sd_rcpp", (DL_FUNC) &_ahead_expand_sd_rcpp, 5},
    {"_ahead_expand_sd_rcpp_fast", (DL_FUNC) &_ahead_expand_sd_rcpp_fast, 4},
    {"_ahead_exact_rf_forecast", (DL_FUNC) &_ahead_exact_rf_forecast, 5},
    {"_ahead_forecast_innovs_loop_cpp", (DL_FUNC) &_ahead_forecast_innovs_loop_cpp, 8},
    {"_ahead_forecast_innovs_loop_cpp2", (DL_FUNC) &_ahead_forecast_innovs_loop_cpp2, 8},
    {"_ahead_create_lags_cpp", (DL_FUNC) &_ahead_create_lags_cpp, 2},
    {"_ahead_create_train_inputs_cpp", (DL_FUNC) &_ahead_create_train_inputs_cpp, 2},
    {"_ahead_reformat_cpp", (DL_FUNC) &_ahead_reformat_cpp, 2},
    {"_ahead_rev_matrix_cpp", (DL_FUNC) &_ahead_rev_matrix_cpp, 1},
    {"_ahead_rbind_vecmat_cpp", (DL_FUNC) &_ahead_rbind_vecmat_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_ahead(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
