# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cosine_attention_cpp <- function(series, window_size = 3L) {
    .Call(`_ahead_cosine_attention_cpp`, series, window_size)
}

exponential_attention_cpp <- function(series, decay_factor = 5.0) {
    .Call(`_ahead_exponential_attention_cpp`, series, decay_factor)
}

dot_product_attention_cpp <- function(series) {
    .Call(`_ahead_dot_product_attention_cpp`, series)
}

scaled_dot_product_attention_cpp <- function(series, temperature = 1.0) {
    .Call(`_ahead_scaled_dot_product_attention_cpp`, series, temperature)
}

gaussian_attention_cpp <- function(series, sigma = 1.0) {
    .Call(`_ahead_gaussian_attention_cpp`, series, sigma)
}

linear_attention_cpp <- function(series) {
    .Call(`_ahead_linear_attention_cpp`, series)
}

value_based_attention_cpp <- function(series, sensitivity = 1.0) {
    .Call(`_ahead_value_based_attention_cpp`, series, sensitivity)
}

hybrid_attention_cpp <- function(series, time_decay = 5.0, value_sensitivity = 1.0) {
    .Call(`_ahead_hybrid_attention_cpp`, series, time_decay, value_sensitivity)
}

parametric_attention_cpp <- function(series, alpha = 0.5, beta = 0.5) {
    .Call(`_ahead_parametric_attention_cpp`, series, alpha, beta)
}

compute_context_vectors_cpp <- function(series, attention_weights) {
    .Call(`_ahead_compute_context_vectors_cpp`, series, attention_weights)
}

compare_attention_mechanisms <- function(series, window_size = 3L, decay_factor = 5.0, temperature = 1.0, sigma = 1.0, sensitivity = 1.0) {
    .Call(`_ahead_compare_attention_mechanisms`, series, window_size, decay_factor, temperature, sigma, sensitivity)
}

exact_rf_forecast <- function(embed_mat, h, lags, predict_func, model) {
    .Call(`_ahead_exact_rf_forecast`, embed_mat, h, lags, predict_func, model)
}

forecast_innovs_loop_cpp <- function(eps, rts, eps_prev, omega, alpha, beta, df, h) {
    .Call(`_ahead_forecast_innovs_loop_cpp`, eps, rts, eps_prev, omega, alpha, beta, df, h)
}

forecast_innovs_loop_cpp2 <- function(eps, rn, eps_prev, omega, alpha, beta, df, h) {
    .Call(`_ahead_forecast_innovs_loop_cpp2`, eps, rn, eps_prev, omega, alpha, beta, df, h)
}

create_lags_cpp <- function(x, k) {
    .Call(`_ahead_create_lags_cpp`, x, k)
}

create_train_inputs_cpp <- function(x, k) {
    .Call(`_ahead_create_train_inputs_cpp`, x, k)
}

reformat_cpp <- function(x, n_k) {
    .Call(`_ahead_reformat_cpp`, x, n_k)
}

rev_matrix_cpp <- function(x) {
    .Call(`_ahead_rev_matrix_cpp`, x)
}

rbind_vecmat_cpp <- function(y, x) {
    .Call(`_ahead_rbind_vecmat_cpp`, y, x)
}

